class MockModelProvider:
    """Temporary model provider before Bedrock integration."""

    def generate(self, prompt: str) -> str:
        return (
            "Mock AI Response\n\n"
            "This response is generated by the shared AI Engine. "
            "In a future sprint, this will call Amazon Bedrock."
        )